[package]
name = "udp_server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio-uring = "0.5.0"

[lib]
name = "lib"
path = "src/lib.rs"

[[bin]]
name = "client"
path = "src/bin/client.rs"

[[bin]]
name = "server"
path = "src/bin/server.rs"
