[package]
name = "udp_server"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
flate2 = "1.1.1"
tokio-uring = "0.5.0"

[[bin]]
name = "client"
path = "src/bin/client.rs"

[[bin]]
name = "server"
path = "src/bin/server.rs"
